stages:
  - test
  - build
  - deploy

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_IMAGE_NAME: $CI_REGISTRY_USER/schedule-service-core

test:
  stage: test
  image: python:3.11.6-slim-bullseye
  only:
    refs:
      - master
  script:
    - pip install poetry==1.4.2
    - poetry env use 3.11
    - poetry install
    - cp .env.example .env
    - poetry run pytest ./schedule_service/tests -v --tb=short
build:
  image: docker:git
  stage: build
  only:
    refs:
      - master
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY/$CI_IMAGE_NAME:$CI_COMMIT_REF_SLUG .
    - docker save -o $CI_IMAGE_NAME.tar $CI_REGISTRY/$CI_IMAGE_NAME:$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - $CI_IMAGE_NAME.tar
deploy:
  image: docker:git
  stage: deploy
  only:
    refs:
      - master
  services:
    - docker:dind
  script:
    - docker load -i $CI_IMAGE_NAME.tar
    - echo "Deployment steps here"
