stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:3.11.6-slim-bullseye
  only:
    refs:
      - master
  script:
    - pip install poetry==1.4.2
    - poetry env use 3.11
    - poetry install
    - cp .env.example .env
    - poetry run pytest ./schedule_service/tests

build:
  image: ubuntu:latest
  only:
    refs:
    - master
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - export IMAGE="coolworldocker/schedule-service-core"
    - export TAG="latest"
    - docker build -t $IMAGE:$TAG .
    - docker push $IMAGE:$TAG
  stage: build

deploy_production:
  image: docker:latest
  only:
    refs:
    - master
  script:
      - echo "NotImplemented"
  stage: deploy
