repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

      - id: black
        name: Format with Black
        entry: poetry run black
        language: system
        types: [ python ]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [ python ]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        types: [ python ]
        entry: pytest
        language: system
        pass_filenames: false

      - id: coverage-badge
        name: coverage-badge
        entry: coverage-badge -f -o assets/coverage.svg
        language: system
        types: [python]
        pass_filenames: false

      - id: extract-openapi
        name: extract-openapi
        entry: python pypi/extract_openapi.py --app-dir=./ --out=pypi/openapi.yaml
        language: system
        types: [python]
        pass_filenames: false
