version: '3.9'

services:
  redis:
    image: bitnami/redis:latest
    command: /opt/bitnami/scripts/redis/run.sh --maxclients 100000
    hostname: schedule-service-redis
    restart: always
    env_file:
      - prod.env
    volumes:
      - redis_data:/bitnami/redis/data
  schedule-service:
    image: rtu_mirea_vuc_schedule:${RTU_MIREA_VUC_SCHEDULE_IMAGE_VERSION:-latest}
    build: ${PWD}
    command: python -m schedule_service
    hostname: schedule-service
    restart: always
    env_file:
      - prod.env
    ports:
      - "8000"
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
    depends_on:
      - redis
volumes:
  redis_data:
