version: "3.9"
services:
  livereloader:
    depends_on:
      - schedule-service
    environment:
      OBSERVER_TYPE: "1"
      RELOAD_LABEL: reload.api
      RESTART_TIMEOUT: "2"
    hostname: schedule-service-livereloader
    image: apogiatzis/livereloading:latest
    networks:
      default: null
    privileged: true
    restart: on-failure
    volumes:
      - type: bind
        source: $PWD/workbook_updater/files
        target: /app/workbook_updater/files
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
  redis:
    command:
      - /opt/bitnami/scripts/redis/run.sh
      - --maxclients
      - "100000"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_AOF_ENABLED: "no"
      REDIS_PORT_NUMBER: "6381"
      SCHEDULE_SERVICE_HOST: 0.0.0.0
      SCHEDULE_SERVICE_LOG_LEVEL: INFO
      SCHEDULE_SERVICE_PORT: "8000"
      SCHEDULE_SERVICE_REDIS_HOST: redis
      SCHEDULE_SERVICE_REDIS_PORT: "6381"
      SCHEDULE_SERVICE_RELOAD: "False"
      SCHEDULE_SERVICE_WORKERS: "1"
      TZ: Europe/Moscow
      WORKBOOK_UPDATER_DAY: '*/1'
      WORKBOOK_UPDATER_HOUR: "3"
    hostname: schedule-service-redis
    image: bitnami/redis:latest
    networks:
      default: null
    restart: always
    user: root
    volumes:
      - type: bind
        source: C:\Users\coolw/volumes/rtu_mirea_vuc_schedule/redis_data
        target: /bitnami/redis/data
  schedule-service:
    build:
      context: $PWD
      dockerfile: Dockerfile
      target: rtu_mirea_vuc_schedule
    command:
      - python
      - -m
      - schedule_service
    depends_on:
      - redis
      - workbook-updater
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_AOF_ENABLED: "no"
      REDIS_PORT_NUMBER: "6381"
      SCHEDULE_SERVICE_HOST: 0.0.0.0
      SCHEDULE_SERVICE_LOG_LEVEL: INFO
      SCHEDULE_SERVICE_PORT: "8000"
      SCHEDULE_SERVICE_REDIS_HOST: redis
      SCHEDULE_SERVICE_REDIS_PORT: "6381"
      SCHEDULE_SERVICE_RELOAD: "False"
      SCHEDULE_SERVICE_WORKERS: "1"
      TZ: Europe/Moscow
      WORKBOOK_UPDATER_DAY: '*/1'
      WORKBOOK_UPDATER_HOUR: "3"
    hostname: schedule-service
    image: rtu_mirea_vuc_schedule:latest
    labels:
      reload.api: "true"
    networks:
      default: null
    restart: always
  workbook-updater:
    build:
      context: $PWD
      dockerfile: Dockerfile
      target: rtu_mirea_vuc_schedule
    command:
      - python
      - -m
      - workbook_updater
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_AOF_ENABLED: "no"
      REDIS_PORT_NUMBER: "6381"
      SCHEDULE_SERVICE_HOST: 0.0.0.0
      SCHEDULE_SERVICE_LOG_LEVEL: INFO
      SCHEDULE_SERVICE_PORT: "8000"
      SCHEDULE_SERVICE_REDIS_HOST: redis
      SCHEDULE_SERVICE_REDIS_PORT: "6381"
      SCHEDULE_SERVICE_RELOAD: "False"
      SCHEDULE_SERVICE_WORKERS: "1"
      TZ: Europe/Moscow
      WORKBOOK_UPDATER_DAY: '*/1'
      WORKBOOK_UPDATER_HOUR: "3"
    hostname: workbook-updater
    image: rtu_mirea_vuc_schedule:latest
    networks:
      default: null
    restart: on-failure
    volumes:
      - type: bind
        source: $PWD/workbook_updater/files
        target: /app/workbook_updater/files
networks:
  default:
    name: rtu_mirea_vuc_schedule_default
