version: '3.9'

services:
  redis:
    extends:
      service: redis
      file: docker-compose.override.yml
    env_file:
      - prod.env
      - ../stack.env
  workbook-updater:
    extends:
      service: workbook-updater
      file: docker-compose.override.yml
    env_file:
      - prod.env
      - ../stack.env
  schedule-service:
    extends:
      service: schedule-service
      file: docker-compose.override.yml
    env_file:
      - prod.env
      - ../stack.env
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
  livereloader:
    extends:
      service: livereloader
      file: docker-compose.override.yml
    env_file:
      - ../stack.env
  prometheus:
    extends:
      service: prometheus
      file: docker-compose.monitoring.yml
    env_file:
      - ../stack.env
  grafana:
    extends:
      service: grafana
      file: docker-compose.monitoring.yml
    env_file:
      - prod.env
      - ../stack.env
