version: '3.9'

services:
  redis:
    image: bitnami/redis:latest
    command: /opt/bitnami/scripts/redis/run.sh --maxclients 100000
    hostname: schedule-service-redis
    restart: always
    env_file:
      - stack.env
    volumes:
      - redis_data:/bitnami/redis/data
  schedule-service:
    image: coolworldocker/rtu_mirea_vuc_schedule:${RTU_MIREA_VUC_SCHEDULE_IMAGE_VERSION:-latest}
    pull_policy: always
    build: .
    command: python -m schedule_service
    hostname: schedule-service
    restart: always
    env_file:
      - stack.env
    ports:
      - "8000"
volumes:
  redis_data:
