version: '3.9'

services:
  locust:
    image: locustio/locust:latest
    command: -f /mnt/locust/locustfile.py --host http://schedule-service:8000/api/v1
    volumes:
      - ./locust/:/mnt/locust
    ports:
      - "8089:8089"
