version: '3.9'

services:
  prometheus:
    user: root
    image: prom/prometheus:latest
    command: --config.file=/etc/prometheus/custom/prometheus.yml
    restart: unless-stopped
    hostname: monitoring-prometheus
    ports:
      - "9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/custom
      - prometheus_data:/prometheus
    env_file:
      - stack.env
  grafana:
    user: root
    image: grafana/grafana:latest
    restart: unless-stopped
    hostname: monitoring-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    env_file:
      - stack.env
volumes:
  prometheus_data:
  grafana_data:
