version: '3.9'

services:
  redis:
    image: bitnami/redis:latest
    user: root
    hostname: schedule-service-redis
    restart: always
    command: /opt/bitnami/scripts/redis/run.sh --maxclients 100000
    volumes:
      - $HOME/volumes/rtu_mirea_vuc_schedule/redis_data:/bitnami/redis/data
  workbook-updater:
    image: rtu_mirea_vuc_schedule:${RTU_MIREA_VUC_SCHEDULE_IMAGE_VERSION:-latest}
    build:
      context: $PWD
      dockerfile: Dockerfile
      target: rtu_mirea_vuc_schedule
    command: python -m workbook_updater
    restart: on-failure
    hostname: workbook-updater
    volumes:
      - $PWD/workbook_updater/files:/app/workbook_updater/files
  schedule-service:
    image: rtu_mirea_vuc_schedule:${RTU_MIREA_VUC_SCHEDULE_IMAGE_VERSION:-latest}
    build:
      context: $PWD
      dockerfile: Dockerfile
      target: rtu_mirea_vuc_schedule
    command: python -m schedule_service
    hostname: schedule-service
    restart: always
    labels:
      reload.api: "true"
    depends_on:
      redis:
        condition: service_started
      workbook-updater:
        condition: service_started
  livereloader:
    image: apogiatzis/livereloading:latest
    privileged: true
    hostname: schedule-service-livereloader
    restart: on-failure
    depends_on:
      schedule-service:
        condition: service_started
    environment:
      RELOAD_LABEL: reload.api
      RESTART_TIMEOUT: 2
      OBSERVER_TYPE: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/workbook_updater/files:/app/workbook_updater/files
