version: '3.9'

services:
  openapi-generator:
    image: openapitools/openapi-generator-cli:latest
    command: >
      generate -i openapi.yaml -g python --library asyncio -o /schedule_service_client --package-name schedule_service_client
    volumes:
    - ./openapi.yaml:/openapi.yaml
    - ./schedule_service_client:/schedule_service_client
    env_file: ../.env
